# -- Site Configuration --
# PaperMod theme configuration
# https://github.com/adityatelange/hugo-PaperMod

theme = "PaperMod"
baseURL = "https://prasanthabr.com/"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "prasanthabr"

enableRobotsTXT = true
summaryLength = 30

buildDrafts = false
buildFuture = false

enableEmoji = true

googleAnalytics = "G-J2B4W0KV6W"

[pagination]
  pagerSize = 25

[imaging]
  anchor = 'Center'

[minify]
  disableXML = true
  minifyOutput = true

[taxonomies]
  domain = "domains"
  status = "statuses"
  intent = "intents"
  tag = "tags"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "domains"
        weight = 80

    [[related.indices]]
        name = "status"
        weight = 60

    [[related.indices]]
        name = "intent"
        weight = 70

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
